spring.application.name=autenticacao

# DB Connection
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:autenticacao}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


logging.level.org.springframework.security=DEBUG

app.security.session.allowed-origin=${SESSION_FRONTEND_ORIGIN:http://localhost:5173}

# Configurações da autenticação por Sessao
server.servlet.session.timeout=${SESSION_TIMEOUT:2h}
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:false}
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.path=/
